version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@changesets/cli"
    versions:
    - 2.13.1
    - 2.14.0
    - 2.14.1
    - 2.15.0
  - dependency-name: typedoc
    versions:
    - 0.20.18
    - 0.20.20
    - 0.20.23
    - 0.20.25
    - 0.20.27
    - 0.20.28
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: typedoc-plugin-markdown
    versions:
    - 3.4.3
    - 3.4.5
  - dependency-name: docusaurus-plugin-typedoc
    versions:
    - 0.7.0
    - 0.9.0
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
